### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by YervandAleksanyan** [DroidsOnRoids/android-animation-disabler#7]
Hi, I am clone repository and run sample test and test crashed with this exception,

 `android.provider.Settings$SettingNotFoundException: window_animation_scale
at android.provider.Settings$Global.getInt(Settings.java:6068)
at pl.droidsonroids.animationdisabler.ExampleTest.animationScalesSetToZeroDuringTest(ExampleTest.kt:17)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:365)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)`
I attach plugin to another project , but animations didn't disable

Thanks

**Comment by koral--** [comment]
`android.provider.Settings$SettingNotFoundException: window_animation_scale` which Android version are you using?

**Comment by YervandAleksanyan** [comment]
> `android.provider.Settings$SettingNotFoundException: window_animation_scale` which Android version are you using?

3.5

**Comment by koral--** [comment]
I mean Android OS version, not the Android Gradle Plugin.

**Comment by YervandAleksanyan** [comment]
> I mean Android OS version, not the Android Gradle Plugin.
19,21,23,24,27,28

**Comment by koral--** [comment]
What is the device model?

**Comment by sovvly** [comment]
Same problem here, samsung note 8 (andorid 7.1.1) and pixel (Andorid 10)

**Comment by koral--** [comment]
Could you change animation scale values manually in system settings app and post output of `adb shell settings list global` (strip sensitive data if any) ?

**Comment by sovvly** [comment]
I changed and got for example window_animation_scale=0.0 from shell command. That what I exactly set it.

**Comment by koral--** [comment]
I've just checked on Pixel with Android 10 and I could not reproduce this issue.
However, I have an idea of potential fix - changing value type from int to float.
I'll fix it ASAP.
